### ISSUE TITLE
Play AudioServices predefined sounds?

### ISSUE THREAD

**Issue by lastObject** [jessesquires/JSQSystemSoundPlayer#29]
hi @jessesquires 

i try user `jsqsystemsoundplayer` to play system alert, as 
http://iphonedevwiki.net/index.php/AudioServices

but it doesn't work.

i tried,
```
[[JSQSystemSoundPlayer sharedPlayer]  playAlertSoundWithFilename:@"/System/Library/Audio/UISounds/sms-received1" fileExtension:kJSQSystemSoundTypeCAF];
```
tried
```
[[JSQSystemSoundPlayer sharedPlayer]  playAlertSoundWithFilename:@"sms-received1" fileExtension:kJSQSystemSoundTypeCAF];
```
tried 
```
[[JSQSystemSoundPlayer sharedPlayer] preloadSoundWithFilename:@"sms-received1" fileExtension:kJSQSystemSoundTypeCAF];
[[JSQSystemSoundPlayer sharedPlayer]  playAlertSoundWithFilename:@"sms-received1" fileExtension:kJSQSystemSoundTypeCAF];
```

this repo called system player, so i reckon it should work.
thanks for you help

**Comment by jessesquires** [comment]
Hey @lastObject ! :smile: 

Ha, so the "system player" name refers to the framework that this library wraps up — [System Sound Services](https://developer.apple.com/library/ios/documentation/AudioToolbox/Reference/SystemSoundServicesReference/index.html) — not to playing actual predefined sounds in AudioServices.

None of your suggestions will work because they are searching `[NSBundle mainBundle]`.

I'm not sure if it's possible to play these predefined sounds on iOS — and it's probably against Apple's guidelines. At least, it probably wouldn't be a good user experience. 

In any case, `SystemSoundID` is simply a `UInt32`, so you could probably pass the SoundIDs listed in [that wiki page](http://iphonedevwiki.net/index.php/AudioServices) to play them — but this would require access to `JSQSystemSoundPlayer` private methods.

**Comment by jessesquires** [comment]
Oh, actually I just tried this and it worked.

If you assign the SoundIDs [from the wiki](http://iphonedevwiki.net/index.php/AudioServices) to [here](
https://github.com/jessesquires/JSQSystemSoundPlayer/blob/develop/Source/JSQSystemSoundPlayer.m#L141), then it works. :tada: 

For example:

```objective-c
SystemSoundID soundID = 1000; // new-mail.caf
```

Maybe this would be cool to support. I've opened #30 to track this.

**Comment by lastObject** [comment]
@jessesquires  

yes, that is what i want. i ll try, thanks
